In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import preprocessing

In [9]:
df=pd.read_csv('/content/Churn_Modelling(Handle Missing Values).csv')

In [10]:
df.head(5)

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           9942 non-null   object
 6   Age              9938 non-null   float64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(3), int64(8), object(3)
memory usage: 1.1+ MB

In [12]:
df.drop(columns=['CustomerId','RowNumber','Surname'],axis=1,inplace=True)

In [13]:
df.head(5)

   CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0          619    France  Female  ...               1        101348.88       1
1          608     Spain  Female  ...               1        112542.58       0
2          502    France  Female  ...               0        113931.57       1
3          699    France  Female  ...               0         93826.63       0
4          850     Spain     NaN  ...               1         79084.10       0

[5 rows x 11 columns]

In [15]:
df.Gender.value_counts()

Gender
Male      5426
Female    4516
Name: count, dtype: int64

#Handling missing values in gender

In [16]:
df.Gender.mode()

0    Male
Name: Gender, dtype: object

In [17]:
df.Gender=df['Gender'].fillna('Male')

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CreditScore      10000 non-null  int64
 1   Geography        10000 non-null  object
 2   Gender           10000 non-null  object
 3   Age              9938 non-null   float64
 4   Tenure           10000 non-null  int64
 5   Balance          10000 non-null  float64
 6   NumOfProducts    10000 non-null  int64
 7   HasCrCard        10000 non-null  int64
 8   IsActiveMember   10000 non-null  int64
 9   EstimatedSalary  10000 non-null  float64
 10  Exited           10000 non-null  int64
dtypes: float64(3), int64(6), object(2)
memory usage: 859.5+ KB

##Label Encoding
Not Recomended

In [22]:
le=preprocessing.LabelEncoder()
df['Gender_label']=le.fit_transform(df.Gender.values)

In [23]:
df.head(5)

   CreditScore Geography  Gender  ...  EstimatedSalary  Exited  Gender_label
0          619    France  Female  ...        101348.88       1             0
1          608     Spain  Female  ...        112542.58       0             0
2          502    France  Female  ...        113931.57       1             0
3          699    France  Female  ...         93826.63       0             0
4          850     Spain    Male  ...         79084.10       0             1

[5 rows x 12 columns]

In [30]:
df.Gender_label.value_counts()

Gender_label
1    5484
0    4516
Name: count, dtype: int64

##One - Hot Encoding

In [35]:
one_hot=pd.get_dummies(df.Geography,dtype=int)

In [36]:
print(one_hot)

      France  Germany  Spain
0          1        0      0
1          0        0      1
2          1        0      0
3          1        0      0
4          0        0      1
...      ...      ...    ...
9995       1        0      0
9996       1        0      0
9997       1        0      0
9998       0        1      0
9999       1        0      0

[10000 rows x 3 columns]

In [37]:
df.head(5)

   CreditScore Geography  Gender  ...  EstimatedSalary  Exited  Gender_label
0          619    France  Female  ...        101348.88       1             0
1          608     Spain  Female  ...        112542.58       0             0
2          502    France  Female  ...        113931.57       1             0
3          699    France  Female  ...         93826.63       0             0
4          850     Spain    Male  ...         79084.10       0             1

[5 rows x 12 columns]

In [39]:
df_dummies=pd.get_dummies(df,dtype=int)
df_dummies.head(5)

   CreditScore   Age  Tenure  ...  Geography_Spain  Gender_Female  Gender_Male
0          619  42.0       2  ...                0              1            0
1          608  41.0       1  ...                1              1            0
2          502  42.0       8  ...                0              1            0
3          699  39.0       1  ...                0              1            0
4          850  43.0       2  ...                1              0            1

[5 rows x 15 columns]

##Dummmy Encoding

In [40]:
df_dummies_de=pd.get_dummies(df,drop_first=True,dtype=int)
df_dummies_de.head(5)

   CreditScore   Age  Tenure  ...  Geography_Germany  Geography_Spain  Gender_Male
0          619  42.0       2  ...                  0                0            0
1          608  41.0       1  ...                  0                1            0
2          502  42.0       8  ...                  0                0            0
3          699  39.0       1  ...                  0                0            0
4          850  43.0       2  ...                  0                1            1

[5 rows x 13 columns]